version: "3.8"

services:
  api:
    container_name: api-lead-scoring
    build:
      context: ./api-lead-scoring
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    container_name: lead-scoring-app
    build:
      context: ./app-lead-scoring
    ports:
      - "5001:5000"
    volumes:
      - ./app-lead-scoring:/app
      - ./models:/app/models:ro
    restart: unless-stopped
