Name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install API deps
        working-directory: api-lead-scoring
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          pip install ruff mypy pytest requests
          ruff --version
          ruff check .

      - name: Type check (mypy)
        run: |
          mypy --version
          mypy api-lead-scoring

      - name: Start API for tests
        working-directory: api-lead-scoring
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 5051 &
          sleep 2

      - name: Run tests
        env:
          API_URL: http://127.0.0.1:5051
        run: pytest -q